"""
---------------------------------------------------------
MediAssist AI - Output Guardrail
---------------------------------------------------------

Purpose
-------
1. Validate final response before sending to user.
2. Prevent empty or invalid responses.
3. Apply basic safety checks.
---------------------------------------------------------
"""

from backend.app_logs.logger import logger


def output_guardrail(state):
    """
    Validate final response generated by Reasoning Agent.
    """

    logger.info("========== Output Guardrail Started ==========")

    try:

        answer = state.get("answer", "")

        # -------------------------------------------------
        # Check empty answer
        # -------------------------------------------------

        if answer is None or not answer.strip():

            logger.warning("Empty answer detected.")

            state["answer"] = (
                "Sorry, I couldn't generate a response."
            )

            logger.info("========== Output Guardrail Completed ==========")

            return state

        # -------------------------------------------------
        # Remove extra whitespace
        # -------------------------------------------------

        answer = answer.strip()

        # -------------------------------------------------
        # Basic hallucination phrases
        # -------------------------------------------------

        blocked_phrases = [
            "i think",
            "i guess",
            "possibly",
            "maybe",
            "probably"
        ]

        answer_lower = answer.lower()

        for phrase in blocked_phrases:

            if phrase in answer_lower:

                logger.warning(
                    f"Potential hallucination phrase detected: {phrase}"
                )

                break

        # -------------------------------------------------
        # Limit response length (optional)
        # -------------------------------------------------

        MAX_LENGTH = 10000

        if len(answer) > MAX_LENGTH:

            logger.warning("Very long response detected.")

            answer = answer[:MAX_LENGTH] + "\n..."

        # -------------------------------------------------
        # Save validated answer
        # -------------------------------------------------

        state["answer"] = answer

        logger.info("Output validation successful.")
        logger.info("========== Output Guardrail Completed ==========")

        return state

    except Exception as e:

        logger.error(f"Output Guardrail Error : {e}")

        state["answer"] = (
            "Unable to generate final response."
        )

        return state